line-length = 120
exclude = [
    "migrations",
    "management/commands/archive",
]


[format]
quote-style = "preserve"


[lint]
select = [
    # Pyflakes
    "F",
    # pycodestyle errors
    "E",
    # pycodestyle warnings
    "W",
    # isort
    "I",
    # pydocstyle
    "D",
]

ignore = [
    "D100",
    "D104",
    "D105",
    "D106",
    "D107",
]


[lint.extend-per-file-ignores]

"apps.py" = [
    "D101",  # missing docstring in public class
    "D102",  # missing docstring in public method
]

"management/commands/*.py" = [
    "D102",  # missing docstring in public method
]

"models.py" = [
    "D102",  # missing docstring in public method
]

"serializers.py" = [
   	"D101",  # missing docstring in public class
	"D102",  # missing docstring in public method
	"D103",  # missing docstring in public function    
]

"decorators.py" = [
    "I001", # Import block is un-sorted or un-formatted
    # ignored because it is passing locally and failing in CI
]

"urls.py" = [
    "I001", # Import block is un-sorted or un-formatted
    # ignored because it is passing locally and failing in CI
]

"views.py" = [
    "I001", # Import block is un-sorted or un-formatted
    # ignored because it is passing locally and failing in CI
]


[lint.pydocstyle]
convention = "google"
